[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'no build step'"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
